### ISSUE TITLE
Feature Request: Better errors when refresh token fails

### ISSUE THREAD

**Issue by dkolb** [Cox-Automotive/alks-cli#134]
I currently utilize `login2fa` to generate refresh tokens to authenticate with ALKS.  My persistent grant seems to expire every 30 days, which is fine and a good security practice.  What is not fine is how alks behaves when my refresh token ceases to work.

```bash
 $ alks sessions open
ALKS v3.0.5
Error: Failed
```

Of course, after a bit of flailing I finally remember the `--verbose` flag.

```bash
 $ alks sessions open --verbose
ALKS v3.0.5
[sessions-open]: getting developer
[sessions-open]: getting auth
[developer]: checking for access token
[sessions-open]: getting accounts
[developer]: retreiving alks account
[developer]: using cached auth object
[api:injectAuth]: getting refresh token
Error: Failed
```

At this point running `alks developer login2fa` and going through the process of regenerating my refresh token resolves the issue.

**Comment by say25** [comment]
Just ran into this myself. I was on ALKS 3.0.3, thought I just needed to upgrade and did so. When I got the error again I came here and after some reading I figured it out but it was more painful than desired :/

**Comment by amagana3** [comment]
This has been fixed in this PR: https://github.com/Cox-Automotive/alks-cli/pull/159
