### ISSUE TITLE
[FEATURE] Print OAuth Link to STDOUT

### ISSUE THREAD

**Issue by webbbarker** [Cox-Automotive/alks-cli#158]
# Feature Request
As a user of the ALKS CLI, I'd really like for it to behave _more_ like a CLI and give me better options for managing out of CLI interactions like retrieving OAuth credentials.  I'd prefer the default behavior to give me a redirect link to the OAuth exchange so I can use my preferred browser.  It'd also be nice to keep the existing behavior with a flag for example, but perhaps one that honors conventions like `$BROWSER` or other system configuration.

**Comment by aaron-seitz** [comment]
(Originally mentioned by Jason Antman)
