### ISSUE TITLE
Enhance .aws/credentials synchronization

### ISSUE THREAD

**Issue by cabarria** [Cox-Automotive/ALKS-CLI#19]
When a new key is requested, automatically add the key to the credentials file using the account alias and role as the profile.

For example,

[coxatlabs27-Admin]
aws_access_key_id=something
aws_secret_access_key=Something Else
aws_session_token=Some Long Stuff

Allow the user to specify if the environment variables and the [default] profile should not be updated; otherwise, update those by default as well.

Anytime a key is updated, perform the appropriate actions to the environment variables and the credentials file.

**Comment by brianantonelli** [comment]
I dont want us to blindly write into `.aws/credentials` without the user's feedback, thats why we support the various output flags (`-o`). What you're describing is possible today, especially with the new sessions subcommand. For example, you can add this to your `~/.bash_profile` so each time you open a terminal window all your sessions will be updated transparently:

`alks sessions open -a '505253542711/ALKSPowerUser - awscoxautolabs6' -r 'PowerUser' -o creds -n 'coxatlabs27-Admin'`

**Comment by cabarria** [comment]
Got it... how about adding it as an option then? And while we add the options, can we have a default options file for ALKS-CLI?

Ideally, I'm looking for something that allows me to update my .aws/credentials file with one command for all the keys I have configured. Those keys will then show up appropriately in any IDE I'm using as well.

Also, not everyone is using bash ;-) Got to think about the Windows folks. I guess they could do something with PowerShell.
