### ISSUE TITLE
Prompt lib output to stderr

### ISSUE THREAD

**Issue by brianantonelli** [Cox-Automotive/alks-cli#40]
Would be a nice feature if we could modify the lib used for the account selection to pipe to stderr instead of stdout. Then you could wrap your session open in an eval and still see the prompts.

**Comment by apottere** [comment]
There's a fun bash workaround for this till it's implemented:
```bash
eval "$(script -q /dev/null alks sessions open -o env 2>&1 | tee >(grep "^export " | tr -d "\r") >&2)"
```

This runs the command with script so it displays the list, forces everything to stdout, copies everything to stderr, and filters stdout to only show the exports.

**Comment by brianantonelli** [comment]
Solved! https://github.com/SBoudrias/Inquirer.js/issues/519#issuecomment-310443441

**Comment by apottere** [comment]
Nice!

**Comment by brianantonelli** [comment]
FWIW that solution didn't exist when I opened it! 🤣

**Comment by brianantonelli** [comment]
Still no luck, its running fine with `stderr` but the library is still outputting some control characters to `stdout`.. 

```
^[[?25l^[[?25hexport AWS_ACCESS_KEY_ID=aaa && export AWS_SECRET_ACCESS_KEY=bbb && export AWS_SESSION_TOKEN=ccc
^[[?25h
```

**Comment by apottere** [comment]
@brianantonelli does that mean this is fixed?

**Comment by brianantonelli** [comment]
Sadly no. Unless we switch to another input framework it most likely wont.

**Comment by apottere** [comment]
![image](https://media.giphy.com/media/7p3e2WCM0VEnm/giphy.gif)
