### ISSUE TITLE
Improve "Error saving developer!" messaging

### ISSUE THREAD

**Issue by kjmiller1** [Cox-Automotive/alks-cli#49]
On my Windows 10 machine, while executing "alks developer configure", and after I select default ALKS account/role I would receive a "Error saving developer" message in the console.

I downloaded the source and added console.error(err.message); to Developer.saveDeveloper callback if(err) block and got a more helpful "ENOENT: no such file or directory, open 'D:\Users\kjmil\alks.db'"

I created a "D:\Users\kjmil\" directory and received a successful "Developer saved!" message.

This is the first time I have used ALKS-CLI so I'm not sure exactly what issue should be resolved, but I think I may be seeing a combination of possible issues:
1) ALKS-CLI probably wanted to use "C:\Users\kjmil\" which does exist instead of "D:\..."
2) Should ALKS-CLI create the directory if it doesn't exist?
3) I didn't dig deeper, but I'm not sure where utils.log(program, logger, 'error saving! ' + err.message); is writing to.  Should a user have to dig deeper to find the log (or hack at the source like me) to view the err.message?

**Comment by brianantonelli** [comment]
Thanks for reporting the issue.. That's very odd that the directory didn't exist, we write our database to your home directory, which on Windows is set under the environment variable `USERPROFILE`. Something seems amiss with the fact that your home directory is set to a directory that doesnt exist - so I wouldn't want the code to arbitrarily create a home directory for you. We have many developers running the CLI on Windows and this is the first I've heard of this error. Do you know why the home directory referenced didn't exist?

Also, if you run the CLI in verbose mode (`-v`) you would have seen the actual error message.

**Comment by kjmiller1** [comment]
Looking at the utils.js#65, it looks like HOMEPATH is used before USERPROFILE.

On my machine, HOMEPATH=\Users\kjmil and USERPROFILE=C:\Users\kjmil.  It looks like since my console was at D:\> and HOMEPATH was used (assuming I'm reading the js correctly), the getFilePathInHome returned D:\Users\kjmil\...

Not sure what kind of side-effects could occur by swapping HOMEPATH || USERPROFILE order but I think it would resolve my issue.

Thanks for the -v tip.
