### ISSUE TITLE
Store alks.db in a ~/.alks folder

### ISSUE THREAD

**Issue by flprmrz** [Cox-Automotive/alks-cli#55]
Just thinking it might be a bit cleaner to store the alks.db file (and any future config files) under a dedicated hidden folder in the user's home dir instead of the home dir root.

**Comment by brianantonelli** [comment]
This was something initially considered, but since we use a database we don't see a need of there ever being more than one file. Its also only visible to the owner, any reason why you think it should be in its own directory?

**Comment by pofallon** [comment]
Maybe use something like https://www.npmjs.com/package/appdirectory to store it (and log files, etc.) in the standard application data location per platform...?  (The ALKS Desktop tool uses something similar provided by Electron).

**Comment by flprmrz** [comment]
No reason really other than asthetics. Just thought I'd mention it. Makes sense though about there only being one file.
