### ISSUE TITLE
Not given all choices for accounts with `alks open sessions`

### ISSUE THREAD

**Issue by MrThomasWagner** [Cox-Automotive/alks-cli#62]
The first time I used the command `alks sessions open`, I was prompted with all of my available accounts to choose from (I have 3 available to me at the portal when I am using a browser).

Now, whenever I use `alks sessions open` I am only able to choose a single account, the first one I ever chose.  

If I run `alks developer accounts` I can see the 3 accounts available to me in the browser.  

I tried uninstalling/reinstalling but did not have any luck.

**Comment by brianantonelli** [comment]
Can you paste the output of `alks sessions open -v` and `alks developer accounts -v`?

**Comment by MrThomasWagner** [comment]
Sorry for the noise.  As soon as I read your comment I realized I was being foolish.  I was only being shown a single account because I was asking for an IAM account, and I only have access to a single IAM account
