### ISSUE TITLE
Add favorites or float used roles up in CLI/UI

### ISSUE THREAD

**Issue by apottere** [Cox-Automotive/alks-cli#65]
It would be great if ALKS remembered which accounts you wanted to use, either by tracking which ones you use most or by adding "favorites".  Often developers have a handful of accounts with a few roles each, which makes finding the correct role annoying.

If ALKS supported favoriting certain roles and put them at the top of the list, it would be much easier.

Bonus points for adding a flag to only show favorites in the CLI!

**Comment by brianantonelli** [comment]
Resolved in 574dd5edbf766ccd6bf55eb3f7d471f25ce10beb
