### ISSUE TITLE
Session getting washed out automatically. And Env var not getting set. Because Developer info getting washed out.

### ISSUE THREAD

**Issue by goyatparmod** [Cox-Automotive/alks-cli#69]
Did following steps 
alks developer configure
alks sessions open
Export AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
But when i do echo $AWS_ACCESS_KEY_ID its blank.
![untitled](https://user-images.githubusercontent.com/13874876/30873639-239c3e0c-a2ab-11e7-832b-6c28826361fd.png)

1. First Env variables not getting set.
2.Also session getting washed out in 10-15 min. 
These issue are pretty random. Does not get those on regular basic. 
I think it happening because Developer info getting washed out.

**Comment by brianantonelli** [comment]
You have to actually run that export, it doesnt set it for you. If you use your default account or specify the account you can evaluate that output:

```
eval $(alks sessions open -d)
eval $(alks sessions open -a "account #"
```
