### ISSUE TITLE
Improve LTK Error Message

### ISSUE THREAD

**Issue by david-woodruff** [Cox-Automotive/alks-cli#91]
So when the `-n` flag is missing the CLI doesn't seem to provide a decent standard error message unless you are running in verbose mode. As far as I can tell even though the message is provided is very similar to what AWS would provide it is baked into the CLI.

A more descriptive error message should be put in place

![image](https://user-images.githubusercontent.com/30657966/41377589-82dd8e7e-6f2a-11e8-9aeb-b57247aa6daf.png)

**Comment by brianantonelli** [comment]
Changed to:

```
🍔  alks iam createltk test -a "$awsaepnp_admin"
ALKS v2.16.0
Please provide a username (-n)
```
